-- ============================================================================
-- 60_admission_decision_terms.sql
-- UniPortal — felvételi folyamat: azonosító, félév, több képzés, döntés
--
-- MIT CSINÁL
--   1) BIZTONSÁGI JAVÍTÁS. Az admission_process_list nézet újra a HÍVÓ jogán fut
--      (security_invoker = on), az anon szerepkör pedig semmit nem olvashat
--      belőle. A 37-es migráció a nézetet e beállítás nélkül építette újra, így a
--      nézet a tulajdonos jogán futott, és az RLS nem érvényesült rajta. MÉRVE
--      élesben (2026-09-15): az oldal forrásában látható anon kulccsal a 35
--      felvételi folyamatból 35 volt lekérdezhető, bejelentkezés nélkül.
--   2) ref_no — ember által olvasható, egyedi folyamat-azonosító (a felületen
--      „FV-00042”). A meglévő sorok a létrehozásuk sorrendjében kapnak számot.
--   3) programs.intakes — melyik félévben indul a képzés: 'autumn' (őszi) és/vagy
--      'spring' (tavaszi). Alapból mindkettő, hogy a migráció semmit ne zárjon le.
--   4) admission_decide() — felvételi döntés: a jelentkező által megjelölt
--      képzések közül melyikre vettük fel, vagy elutasítás. A data.decision-be ír.
--   5) A data.decision kulcsot a jelentkező nem írhatja: a hallgatói felület a
--      teljes data mezőt visszamenti, és egy régi példány eltüntetné a döntést
--      (vagy egy rosszindulatú kérés hamisítana egyet).
--
-- A több képzésre szóló jelentkezés és a félév a data mezőben él
-- (data.program_ids, data.term): ehhez nem kell oszlop, a felület a migráció
-- előtt is tudja menteni. Idempotens, többször is lefuttatható.
-- ============================================================================

begin;

-- A számozás és az azonosító-oszlop felvétele közben ne szülessen új sor.
lock table public.admission_processes in exclusive mode;

-- ---------------------------------------------------------------------------
-- 2) ref_no — folyamat-azonosító
-- ---------------------------------------------------------------------------
alter table public.admission_processes add column if not exists ref_no bigint;

-- A created_at szöveg, vegyes alakban („2026.06.27” és ISO). Hibás értéknél a
-- számozás nem állhat meg, ezért a dátumot hibatűrő segédfüggvény olvassa.
create or replace function pg_temp.uniportal_datum(p text)
returns timestamptz language plpgsql immutable as $fn$
begin
  if p ~ '^\d{4}\.\d{2}\.\d{2}' then return to_date(substr(p, 1, 10), 'YYYY.MM.DD')::timestamptz; end if;
  if p ~ '^\d{4}-\d{2}-\d{2}'  then return substr(p, 1, 10)::date::timestamptz; end if;
  return null;
exception when others then
  return null;
end $fn$;

with rendezett as (
  select p.id,
         row_number() over (order by coalesce(pg_temp.uniportal_datum(p.created_at), p.updated_at), p.id) as rn
    from public.admission_processes p
   where p.ref_no is null
)
update public.admission_processes p
   set ref_no = r.rn + coalesce((select max(x.ref_no) from public.admission_processes x), 0)
  from rendezett r
 where p.id = r.id;

-- Identitást csak NOT NULL oszlopra enged a Postgres.
alter table public.admission_processes alter column ref_no set not null;

do $$
declare
  v_start bigint;
begin
  if not exists (
       select 1
         from pg_attribute a
         join pg_class c     on c.oid = a.attrelid
         join pg_namespace n on n.oid = c.relnamespace
        where n.nspname = 'public' and c.relname = 'admission_processes'
          and a.attname = 'ref_no' and a.attidentity <> '') then
    select coalesce(max(ref_no), 0) + 1 into v_start from public.admission_processes;
    execute format('alter table public.admission_processes alter column ref_no add generated by default as identity (start with %s)', v_start);
  end if;
end $$;

create unique index if not exists admission_processes_ref_no_key on public.admission_processes (ref_no);

comment on column public.admission_processes.ref_no is
  'Ember által olvasható folyamat-azonosító; a felület FV-00042 alakban mutatja.';

-- ---------------------------------------------------------------------------
-- 1) A listanézet — újra a hívó jogán, az új oszloppal
--    A dataUrl kiszűrése MEGMARAD: a lista soha ne hordozzon fájlbájtokat.
-- ---------------------------------------------------------------------------
drop view if exists public.admission_process_list;
create view public.admission_process_list
  with (security_invoker = on)
as
  select
    p.id,
    p.ref_no,
    p.owner_email,
    p.step,
    p.max_reached,
    p.done,
    p.created_at,
    p.updated_at,
    p.program_id,
    p.applicant_name,
    p.stage,
    p.student_step,
    p.submitted_at,
    coalesce(p.data, '{}'::jsonb) || jsonb_build_object(
      'docs',
      coalesce((
        select jsonb_object_agg(d.key, d.value - 'dataUrl')
          from jsonb_each(coalesce(p.data -> 'docs', '{}'::jsonb)) d(key, value)
      ), '{}'::jsonb)
    ) as data
  from public.admission_processes p;

-- A Supabase alapjogosultsága az anon-nak is mindent megad az új nézeten.
revoke all on public.admission_process_list from public, anon;
grant select on public.admission_process_list to authenticated;

-- ---------------------------------------------------------------------------
-- 3) programs.intakes — az indulás féléve(i)
-- ---------------------------------------------------------------------------
alter table public.programs
  add column if not exists intakes text[] not null default array['autumn', 'spring']::text[];

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'programs_intakes_ck') then
    alter table public.programs add constraint programs_intakes_ck
      check (cardinality(intakes) between 1 and 2 and intakes <@ array['autumn', 'spring']::text[]);
  end if;
end $$;

comment on column public.programs.intakes is
  'Melyik félévben indul a képzés: autumn = őszi, spring = tavaszi. A jelentkező csak ezekre a félévekre jelentkezhet.';

-- ---------------------------------------------------------------------------
-- 5) A hivatali kulcsok védelme a data mezőben
--    Csak a KÖZVETLEN (PostgREST) írást fogjuk meg: ott a current_user
--    'authenticated'. A SECURITY DEFINER RPC-k a függvény tulajdonosaként
--    futnak — ők írják ezeket a kulcsokat. Az ügyintéző közvetlenül is írhat.
--    A kulcslistát a 61-es migráció bővíti (interjú).
-- ---------------------------------------------------------------------------
create or replace function public.admission_office_keys()
returns text[] language sql immutable as $fn$
  select array['decision']::text[]
$fn$;

revoke all on function public.admission_office_keys() from public, anon;
grant execute on function public.admission_office_keys() to authenticated;

create or replace function public.admission_processes_protect_office_keys()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $fn$
declare
  k text;
begin
  if current_user not in ('authenticated', 'anon') then
    return new;
  end if;
  if coalesce(public.is_staff(), false) then
    return new;
  end if;
  foreach k in array public.admission_office_keys() loop
    if tg_op = 'UPDATE' and old.data ? k then
      new.data := jsonb_set(coalesce(new.data, '{}'::jsonb), array[k], old.data -> k, true);
    else
      new.data := coalesce(new.data, '{}'::jsonb) - k;
    end if;
  end loop;
  return new;
end
$fn$;

drop trigger if exists admission_processes_protect_office_keys_trg on public.admission_processes;
create trigger admission_processes_protect_office_keys_trg
  before insert or update on public.admission_processes
  for each row execute function public.admission_processes_protect_office_keys();

-- ---------------------------------------------------------------------------
-- 4) Felvételi döntés — public.admission_decide()
--    p_outcome: admitted (felvéve) | rejected (elutasítva) | withdrawn
--    (visszalépett) | pending (a döntés visszavonása).
--    Felvételnél a képzésnek a jelentkező által megjelölt képzések között kell
--    lennie; ha csak egyet jelölt meg, azt nem kötelező külön megadni.
-- ---------------------------------------------------------------------------
create or replace function public.admission_decide(
  p_id         text,
  p_outcome    text,
  p_program_id text default null,
  p_note       text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_row      public.admission_processes;
  v_allowed  text[];
  v_program  text := nullif(btrim(coalesce(p_program_id, '')), '');
  v_decision jsonb;
  v_name     text;
begin
  if not coalesce(public.is_admissions(), false) then
    raise exception 'Felvételi döntést csak a felvételi iroda munkatársa hozhat.' using errcode = '42501';
  end if;
  if coalesce(p_outcome, '') not in ('admitted', 'rejected', 'withdrawn', 'pending') then
    raise exception 'Ismeretlen döntés: % (admitted / rejected / withdrawn / pending).', p_outcome using errcode = '22023';
  end if;

  select * into v_row from public.admission_processes where id = p_id for update;
  if v_row.id is null then
    raise exception 'Nincs ilyen felvételi folyamat: %', p_id using errcode = '02000';
  end if;

  select array_agg(distinct s.x) into v_allowed
    from (
      select v_row.program_id as x
      union all
      select jsonb_array_elements_text(case when jsonb_typeof(v_row.data -> 'program_ids') = 'array' then v_row.data -> 'program_ids' else '[]'::jsonb end)
      union all
      select jsonb_array_elements_text(case when jsonb_typeof(v_row.data -> 'programs') = 'array' then v_row.data -> 'programs' else '[]'::jsonb end)
    ) s
   where nullif(btrim(coalesce(s.x, '')), '') is not null;

  if p_outcome = 'admitted' then
    if v_program is null then
      if coalesce(array_length(v_allowed, 1), 0) = 1 then
        v_program := v_allowed[1];
      else
        raise exception 'Felvételnél meg kell adni, melyik képzésre vettük fel a jelentkezőt.' using errcode = '22023';
      end if;
    elsif not (v_program = any (coalesce(v_allowed, '{}'::text[]))) then
      raise exception 'A(z) "%" képzés nem szerepel a jelentkező által megjelölt képzések között.', v_program using errcode = '22023';
    end if;
  else
    v_program := null;
  end if;

  select coalesce(nullif(btrim(pr.name), ''), pr.email) into v_name from public.profiles pr where pr.id = auth.uid();

  if p_outcome = 'pending' then
    update public.admission_processes
       set data = coalesce(data, '{}'::jsonb) - 'decision', updated_at = now()
     where id = p_id;
    return jsonb_build_object('id', p_id, 'decision', null);
  end if;

  v_decision := jsonb_build_object(
    'outcome',   p_outcome,
    'programId', v_program,
    'note',      nullif(btrim(coalesce(p_note, '')), ''),
    'at',        now(),
    'by',        auth.uid(),
    'byName',    v_name);

  update public.admission_processes
     set data = jsonb_set(coalesce(data, '{}'::jsonb), '{decision}', v_decision, true),
         updated_at = now()
   where id = p_id;

  return jsonb_build_object('id', p_id, 'decision', v_decision);
end
$fn$;

comment on function public.admission_decide(text, text, text, text) is
  'Felvételi döntés rögzítése (felvéve a megjelölt képzések egyikére / elutasítva / visszalépett / visszavonás).';

revoke all on function public.admission_decide(text, text, text, text) from public, anon;
grant execute on function public.admission_decide(text, text, text, text) to authenticated;

-- ---------------------------------------------------------------------------
-- 6) Záró ellenőrzés
-- ---------------------------------------------------------------------------
do $$
declare
  v_opts text[];
begin
  select c.reloptions into v_opts
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relname = 'admission_process_list';
  if not (coalesce(v_opts, '{}'::text[]) && array['security_invoker=on', 'security_invoker=true']) then
    raise exception 'BIZTONSAGI HIBA: az admission_process_list nezet nem a hivo jogan fut (security_invoker).';
  end if;
  if exists (select 1 from pg_roles where rolname = 'anon')
     and has_table_privilege('anon', 'public.admission_process_list', 'select') then
    raise exception 'BIZTONSAGI HIBA: az anon olvashatja az admission_process_list nezetet.';
  end if;
  if exists (select 1 from public.admission_processes where ref_no is null) then
    raise exception 'HIBA: maradt azonosito nelkuli felveteli folyamat.';
  end if;
  raise notice 'Rendben: 60 — % folyamat kapott azonosítót, a listanézet az RLS-t követi (anon nem olvassa), programs.intakes és admission_decide() kész.',
    (select count(*) from public.admission_processes);
end $$;

commit;
