-- ============================================================================
-- 68_echo_campaign_ref_no.sql — inkrementális kampányazonosító (K-0001, K-0002…)
--
-- MIÉRT KELL
--   Minden kampánynak legyen egy rövid, egyesével növekvő azonosítója, amit az
--   admin és a hallgatói felület is kiír (hibajelzésnél, telefonon bemondható).
--   A meglévő 'code' (pl. OMHV-2026-27-1-14) megmarad — más logika használja —,
--   a felület a sorszámot mutatja, a kódot csak buboréksúgóban.
--
-- MINTA: 60_admission_decision_terms.sql, admission_processes.ref_no.
--   * a meglévő kampányok created_at (majd id) sorrendben kapnak számot;
--   * utána identity (start = max+1), egyedi index;
--   * a sorszámot soha nem írja újra semmi (generated BY DEFAULT, de egyetlen
--     RPC sem ad meg értéket).
--
-- FÜGGVÉNYEK: az echo_campaigns() (15) és az echo_my_courses() (22, a legutóbbi
--   definíció) törzse BETŰRE VÁLTOZATLAN, csak a 'ref_no' / 'campaign_ref_no'
--   kulcs új. A felület a migráció előtt is működik (a régi kódot mutatja).
--
-- IDEMPOTENS: igen (kétszer futtatva is hibátlan).
-- UTÁNA: a 21_echo_harden_submit.sql újrafuttatása (a szokásos szabály szerint).
-- ============================================================================

alter table echo.campaign add column if not exists ref_no bigint;

with rendezett as (
  select c.id, row_number() over (order by c.created_at, c.opens_at, c.id) as rn
    from echo.campaign c
   where c.ref_no is null
)
update echo.campaign c
   set ref_no = r.rn + coalesce((select max(x.ref_no) from echo.campaign x), 0)
  from rendezett r
 where c.id = r.id;

alter table echo.campaign alter column ref_no set not null;

do $blk$
declare
  v_start bigint;
begin
  if not exists (
       select 1
         from pg_attribute a
         join pg_class c     on c.oid = a.attrelid
         join pg_namespace n on n.oid = c.relnamespace
        where n.nspname = 'echo' and c.relname = 'campaign'
          and a.attname = 'ref_no' and a.attidentity <> '') then
    select coalesce(max(ref_no), 0) + 1 into v_start from echo.campaign;
    execute format('alter table echo.campaign alter column ref_no add generated by default as identity (start with %s)', v_start);
  end if;
end $blk$;

create unique index if not exists echo_campaign_ref_no_uidx on echo.campaign (ref_no);

comment on column echo.campaign.ref_no is
  'Inkrementális kampányazonosító; a felületen K-0001 alakban jelenik meg (68).';

create or replace function public.echo_campaigns()
returns jsonb
language plpgsql stable security definer
set search_path = echo, public, extensions, pg_temp
as $$
declare v_out jsonb;
begin
  -- is_admin() es NEM is_staff(): a menuben az 'ECHO kampanyok' csak
  -- SUPERADMIN/ADMIN-nak latszik, az is_staff() viszont az ADMISSIONS-t es a
  -- FINANCE-t is beengedne — vagyis ok a bongeszo konzoljabol elerhetnek egy
  -- olyan RPC-t, amit a felulet szerint nem lathatnak. A felulet es az API
  -- hatarat egy helyre hozzuk. (Tartalom eddig sem szivargott: mindket RPC
  -- kizarolag darabszamot ad vissza.)
  if not public.is_admin() then raise exception 'ECHO_FORBIDDEN'; end if;
  select coalesce(jsonb_agg(x order by x->>'opens_at' desc), '[]'::jsonb) into v_out
  from (
    select jsonb_build_object(
             'id', c.id, 'code', c.code, 'ref_no', c.ref_no, 'name', c.name_hu, 'term', c.term,
             'state', c.state, 'opens_at', c.opens_at, 'closes_at', c.closes_at,
             'is_open', echo.is_open(c.id),
             'template_version_id', c.template_version_id,
             'eligible_courses', (select count(distinct course_id) from echo.eligibility
                                   where campaign_id = c.id),
             'eligible_pairs',   (select count(*) from echo.eligibility where campaign_id = c.id),
             'eligible_students',(select count(*) from echo.participation
                                   where campaign_id = c.id and eligible),
             'attempted',        (select count(*) from echo.participation
                                   where campaign_id = c.id and attempted),
             'responses',        (select count(*) from echo.response
                                   where campaign_id = c.id and scope = 'course'),
             'excluded_courses', (select count(distinct course_id) from echo.exclusion_log
                                   where campaign_id = c.id and teacher_id is null),
             'kitoltesi_arany',  round(
                (select count(*) from echo.response where campaign_id = c.id and scope='course')::numeric
                / nullif((select count(*) from echo.participation
                           where campaign_id = c.id and eligible), 0) * 100, 1)
           ) as x
      from echo.campaign c
  ) s;
  return v_out;
end $$;

create or replace function public.echo_my_courses()
returns jsonb
language plpgsql
stable security definer
set search_path to 'echo', 'public', 'extensions', 'pg_temp'
as $$
declare v_me uuid := auth.uid(); v_out jsonb;
begin
  if v_me is null then raise exception 'ECHO_NOT_AUTHENTICATED'; end if;
  if not public.is_approved() then raise exception 'ECHO_NOT_APPROVED'; end if;

  select coalesce(jsonb_agg(x order by x->>'closes_at', x->>'course_name'), '[]'::jsonb)
    into v_out
  from (
    select jsonb_build_object(
             'campaign_id',    c.id,
             'campaign_code',  c.code,
             'campaign_ref_no', c.ref_no,
             'campaign_name',  c.name_hu,
             'campaign_state', c.state,
             'term',           c.term,
             'opens_at',       c.opens_at,
             'closes_at',      c.closes_at,
             'is_open',        echo.is_open(c.id),
             'is_goals_open',  echo.is_goals_open(c.id),
             'course_id',      k.id,
             'course_code',    k.code,
             'course_name',    k.name_hu,
             'course_name_en', k.name_en,
             'lang',           k.lang,
             'teacher_count',  (select count(*) from echo.eligibility el
                                 where el.campaign_id = c.id and el.course_id = k.id),
             'goals_saved',    exists (select 1 from echo.student_goal g
                                        where g.campaign_id = c.id and g.course_id = k.id
                                          and g.student_key = v_me
                                          and jsonb_array_length(g.goals) > 0),
             'attempted',      p.attempted,
             'submitted',      p.submitted,
             -- A piszkozat LÉTE és a lépésszám megy vissza, a TARTALMA SOHA.
             -- Ez a hívó saját sora (student_key = v_me), tehát nem szivárgás.
             'has_draft',      (d.student_key is not null),
             'draft_step',     d.step,
             'draft_saved',    d.updated_at,
             -- Osszefoglalo allapot a felulet szamara:
             'allapot',
               case when p.submitted                        then 'kitoltve'
                    when echo.is_open(c.id) and d.student_key is not null
                                                            then 'felbehagyott'
                    when echo.is_open(c.id) and p.attempted then 'folyamatban'
                    when echo.is_open(c.id)                 then 'kitoltheto'
                    when echo.is_goals_open(c.id)           then 'celkituzes'
                    when c.state in ('closed','processing','sealed','published') then 'lezart'
                    else 'nem_nyitott' end
           ) as x
      from echo.participation p
      join echo.campaign c on c.id = p.campaign_id
      join echo.course   k on k.id = p.course_id
      -- BAL oldali join: a lejárt piszkozat úgy számít, mintha nem lenne
      -- (ugyanaz a szabály, mint az echo_draft_get()-ben).
      left join echo.draft d
             on d.campaign_id = p.campaign_id
            and d.course_id   = p.course_id
            and d.student_key = v_me
            and d.expires_at  >= now()
     where p.student_key = v_me
       and p.eligible
       and c.state <> 'draft'
  ) s;

  return v_out;
end $$;

revoke all on function public.echo_campaigns()  from public;
revoke all on function public.echo_campaigns()  from anon;
grant execute on function public.echo_campaigns()  to authenticated;
revoke all on function public.echo_my_courses() from public;
revoke all on function public.echo_my_courses() from anon;
grant execute on function public.echo_my_courses() to authenticated;

do $blk$
begin
  if has_function_privilege('anon', 'public.echo_campaigns()', 'execute')
     or has_function_privilege('anon', 'public.echo_my_courses()', 'execute') then
    raise exception 'BIZTONSAGI HIBA: az anon hivhatja az echo_campaigns / echo_my_courses fuggvenyt.';
  end if;
  if exists (select 1 from echo.campaign where ref_no is null) then
    raise exception 'HIBA: maradt sorszam nelkuli kampany.';
  end if;
  raise notice 'Rendben: 68 — inkrementalis kampanyazonosito (ref_no) bevezetve.';
end $blk$;
